version: '3.3'

services:
  postgres:
    image: ${IMAGE}
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    # depends_on:
    #   - postgres

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - ${MYSQL_MY_PORT}:${MYSQL_PORT}
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD:${DB_PASSWORD}
      - PMA_HOST=mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
